[tool.poetry]
name = "pybuoy"
version = "0.4.3"
authors = ["Kyle J. Burda <kylejbdev@gmail.com>"]
classifiers=[
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.10",
]
description = "Python wrapper for NDBC data."
documentation = "https://pybuoy.readthedocs.io"
include = ["LICENSE"]
keywords=["NDBC", "NOAA", "api", "buoy", "weather", "wrapper"]
license = "GPL-3.0-or-later"
readme = "README.rst"

[tool.poetry.urls]
"Source Code" = "https://github.com/clairBuoyant/pybuoy"
"Bug Tracker" = "https://github.com/clairBuoyant/pybuoy/issues"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.2"

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
flake8 = "^6.0.0"
isort = { version = "^5.12.0", extras = ["pyproject"]}
mypy = "^1.00"
pytest = "^7.2.1"
pre-commit = "^3.0.4"
types-requests = "^2.28.11"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
Sphinx = "^6.1.3"
furo = "^2022.12.7"

[tool.black]
line-length = 88
target_version = ['py310']
exclude = '''
(
  /(
    \.git
    | \.github
    | \.mypy_cache
    | \.pytest_cache
    | dist
    | htmlcov
    | .venv
  )/
)
'''

[tool.isort]
profile="black"

[tool.mypy]
namespace_packages = true
explicit_package_bases = true
exclude = '''
(
  /(
    \.git
    | dist
    | docs/source/conf.py
    | .venv
  )/
)
'''

[tool.pytest.ini_options]
minversion = "7.0"
testpaths = [
    "tests",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
