[tool.poetry]
name = "buoy-py"
version = "0.1.0"
description = "Python wrapper for NDBC data."
authors = ["Kyle J. Burda <47502769+kylejb@users.noreply.github.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pre-commit = "^2.19.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
